//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pracownia.BmwWawa {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarWawa", Namespace="http://schemas.datacontract.org/2004/07/BMW_Wawa.DO")]
    [System.SerializableAttribute()]
    public partial class CarWawa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KolorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MocField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NadwozieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PojemnoscField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SilnikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SkrzyniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WersjaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cena {
            get {
                return this.CenaField;
            }
            set {
                if ((this.CenaField.Equals(value) != true)) {
                    this.CenaField = value;
                    this.RaisePropertyChanged("Cena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kolor {
            get {
                return this.KolorField;
            }
            set {
                if ((object.ReferenceEquals(this.KolorField, value) != true)) {
                    this.KolorField = value;
                    this.RaisePropertyChanged("Kolor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moc {
            get {
                return this.MocField;
            }
            set {
                if ((this.MocField.Equals(value) != true)) {
                    this.MocField = value;
                    this.RaisePropertyChanged("Moc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nadwozie {
            get {
                return this.NadwozieField;
            }
            set {
                if ((object.ReferenceEquals(this.NadwozieField, value) != true)) {
                    this.NadwozieField = value;
                    this.RaisePropertyChanged("Nadwozie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pojemnosc {
            get {
                return this.PojemnoscField;
            }
            set {
                if ((this.PojemnoscField.Equals(value) != true)) {
                    this.PojemnoscField = value;
                    this.RaisePropertyChanged("Pojemnosc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Seria {
            get {
                return this.SeriaField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriaField, value) != true)) {
                    this.SeriaField = value;
                    this.RaisePropertyChanged("Seria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Silnik {
            get {
                return this.SilnikField;
            }
            set {
                if ((this.SilnikField.Equals(value) != true)) {
                    this.SilnikField = value;
                    this.RaisePropertyChanged("Silnik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Skrzynia {
            get {
                return this.SkrzyniaField;
            }
            set {
                if ((this.SkrzyniaField.Equals(value) != true)) {
                    this.SkrzyniaField = value;
                    this.RaisePropertyChanged("Skrzynia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Wersja {
            get {
                return this.WersjaField;
            }
            set {
                if ((object.ReferenceEquals(this.WersjaField, value) != true)) {
                    this.WersjaField = value;
                    this.RaisePropertyChanged("Wersja");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BmwWawa.IBMWWawa")]
    public interface IBMWWawa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBMWWawa/GetCars", ReplyAction="http://tempuri.org/IBMWWawa/GetCarsResponse")]
        Pracownia.BmwWawa.CarWawa[] GetCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBMWWawa/GetCars", ReplyAction="http://tempuri.org/IBMWWawa/GetCarsResponse")]
        System.Threading.Tasks.Task<Pracownia.BmwWawa.CarWawa[]> GetCarsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBMWWawaChannel : Pracownia.BmwWawa.IBMWWawa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BMWWawaClient : System.ServiceModel.ClientBase<Pracownia.BmwWawa.IBMWWawa>, Pracownia.BmwWawa.IBMWWawa {
        
        public BMWWawaClient() {
        }
        
        public BMWWawaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BMWWawaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BMWWawaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BMWWawaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pracownia.BmwWawa.CarWawa[] GetCars() {
            return base.Channel.GetCars();
        }
        
        public System.Threading.Tasks.Task<Pracownia.BmwWawa.CarWawa[]> GetCarsAsync() {
            return base.Channel.GetCarsAsync();
        }
    }
}
